CREATE TABLE accents (
    Kacc INT(11) AUTO_INCREMENT NOT NULL,
    LibSAcc VARCHAR(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    LibAcc VARCHAR(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Kacc)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE accounts (
    login VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
    kage INT(11) NOT NULL,
    cid INT(11) AUTO_INCREMENT NOT NULL,
    PRIMARY KEY (cid)
) ENGINE=MyISAM COLLATE=utf8_general_ci;
CREATE TABLE activites (
    Kact INT(11) AUTO_INCREMENT NOT NULL,
    Kage INT(11) NOT NULL,
    Kann INT(11) NOT NULL,
    LibAct VARCHAR(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    ActLie TINYINT(4) NOT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Kact)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE adresses (
    Kadr INT(11) AUTO_INCREMENT NOT NULL,
    Kpos INT(11) NULL DEFAULT NULL,
    Kdep INT(11) NULL DEFAULT NULL,
    Kpay INT(11) NULL DEFAULT NULL,
    Adresse LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Perso TINYINT(4) NULL DEFAULT NULL,
    Type INT(11) NULL DEFAULT NULL,
    Verrou VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Date_derniere_modif DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (Kadr)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE ageaut (
    Kaat INT(11) AUTO_INCREMENT NOT NULL,
    Kpie INT(11) NOT NULL,
    Ksig INT(11) NOT NULL,
    DatAutV DATETIME NULL DEFAULT NULL,
    DatDebV DATETIME NULL DEFAULT NULL,
    DatFinV DATETIME NULL DEFAULT NULL,
    NumAut VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Kaat)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE ageautpers (
    Kaap INT(11) AUTO_INCREMENT NOT NULL,
    Kpie INT(11) NOT NULL,
    Kvmk INT(11) NULL DEFAULT NULL,
    Kvmd INT(11) NULL DEFAULT NULL,
    Kvas INT(11) NULL DEFAULT NULL,
    Ksig INT(11) NOT NULL,
    DatAut DATETIME NULL DEFAULT NULL,
    Ponct TINYINT(4) NOT NULL,
    Immat VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    NumPol VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Zone INT(11) NULL DEFAULT NULL,
    KmAut DOUBLE NULL DEFAULT NULL,
    KmAdd DOUBLE NULL DEFAULT NULL,
    DatDeb DATETIME NULL DEFAULT NULL,
    DatFin DATETIME NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Kaap)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE agecode (
    Kcod INT(11) AUTO_INCREMENT NOT NULL,
    Kage INT(11) NOT NULL,
    CodConf VARCHAR(4) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    CodChauf VARCHAR(4) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Kcod)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE ageetat (
    Keta INT(11) AUTO_INCREMENT NOT NULL,
    Kpst INT(11) NOT NULL,
    Kage INT(11) NOT NULL,
    Ketsnew INT(11) NOT NULL,
    Kuninew INT(11) NULL DEFAULT NULL,
    Ksubnew INT(11) NULL DEFAULT NULL,
    Ksernew INT(11) NULL DEFAULT NULL,
    Ketsex INT(11) NULL DEFAULT NULL,
    Kuniex INT(11) NULL DEFAULT NULL,
    Ksubex INT(11) NULL DEFAULT NULL,
    Kserex INT(11) NULL DEFAULT NULL,
    DatCre DATETIME NULL DEFAULT NULL,
    Arrivee VARCHAR(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Motif VARCHAR(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    DatEta DATETIME NULL DEFAULT NULL,
    DatCPA DATE NULL DEFAULT NULL,
    DatCFA DATETIME NULL DEFAULT NULL,
    DatRet DATETIME NULL DEFAULT NULL,
    PosFutur INT(11) NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Keta)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE agents (
    Kage INT(11) AUTO_INCREMENT NOT NULL,
    Kuni INT(11) NULL DEFAULT NULL,
    Ksub INT(11) NULL DEFAULT NULL,
    Kser INT(11) NULL DEFAULT NULL,
    Kbat INT(11) NULL DEFAULT NULL,
    Kgra INT(11) NULL DEFAULT NULL,
    Kbur INT(11) NULL DEFAULT NULL,
    Kres INT(11) NULL DEFAULT NULL,
    Ksec INT(11) NULL DEFAULT NULL,
    Nom VARCHAR(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Prenom VARCHAR(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Matri VARCHAR(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
    DatCre DATETIME NULL DEFAULT NULL,
    DatOuv DATETIME NULL DEFAULT NULL,
    DatMod DATETIME NULL DEFAULT NULL,
    DatClo DATETIME NULL DEFAULT NULL,
    HorSect VARCHAR(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    CodHie SMALLINT(6) NULL DEFAULT NULL,
    CodHor VARCHAR(6) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    LibHor VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Telephone VARCHAR(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Poste VARCHAR(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Fax VARCHAR(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Portable VARCHAR(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Bureau VARCHAR(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    RoleDeta LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    DatMaj DATETIME NULL DEFAULT NULL,
    DatNai DATETIME NULL DEFAULT NULL,
    VilNai VARCHAR(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    DepNai VARCHAR(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    NomPre VARCHAR(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Actif TINYINT(4) NOT NULL,
    IneTP SMALLINT(6) NULL DEFAULT NULL,
    HSLabo SMALLINT(6) NULL DEFAULT NULL,
    MissioLabo TINYINT(4) NOT NULL,
    LogUse VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    NumImmo VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    INSEE VARCHAR(16) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Circe TINYINT(4) NOT NULL,
    PaysNai VARCHAR(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Signat TINYINT(4) NOT NULL,
    Temptation TINYINT(4) NOT NULL,
    Verrou VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    NumautCond INT(11) NULL DEFAULT NULL,
    Autorise INT(11) NULL DEFAULT NULL,
    INM CHAR(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    AgGesper VARCHAR(12) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    AgRe VARCHAR(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    AgRisques INT(11) NULL DEFAULT NULL,
    Ksec2 INT(11) NULL DEFAULT NULL,
    REHUCIT VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    libelle_poste LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    dossier_d INT(11) NULL DEFAULT NULL,
    dossier_r INT(11) NULL DEFAULT NULL,
    libelle_doc LONGBLOB NOT NULL,
    PRIMARY KEY (Kage)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE agentsbpc (
    Kage INT(11) NOT NULL,
    Kpos INT(11) NULL DEFAULT NULL,
    Kres INT(11) NULL DEFAULT NULL,
    Nom VARCHAR(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Prenom VARCHAR(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Matri VARCHAR(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
    Adresse LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    AdrePers LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE ageperm (
    Kape INT(11) AUTO_INCREMENT NOT NULL,
    Kcpe INT(11) NULL DEFAULT NULL,
    Kage INT(11) NULL DEFAULT NULL,
    NumPerm VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    DatObt DATETIME NULL DEFAULT NULL,
    Verrou BLOB NULL DEFAULT NULL,
    PRIMARY KEY (Kape)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE agepiece (
    Kpie INT(11) AUTO_INCREMENT NOT NULL,
    Kcpe INT(11) NULL DEFAULT NULL,
    Kage INT(11) NOT NULL,
    TypPie INT(11) NOT NULL,
    NumPie VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    DatPie DATETIME NULL DEFAULT NULL,
    DatVal DATETIME NULL DEFAULT NULL,
    SignPie VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Kpie)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE agerol (
    Kagr INT(11) AUTO_INCREMENT NOT NULL,
    Kage INT(11) NOT NULL,
    Krol INT(11) NOT NULL,
    Priorite INT(11) NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Kagr)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE annexes (
    Kann INT(11) AUTO_INCREMENT NOT NULL,
    Krol INT(11) NULL DEFAULT NULL,
    LibAnnc VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    LibAnn VARCHAR(200) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Lie TINYINT(4) NOT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Kann)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE backupagents (
    Kage INT(11) NOT NULL,
    Kuni INT(11) NULL DEFAULT NULL,
    Ksub INT(11) NULL DEFAULT NULL,
    Kser INT(11) NULL DEFAULT NULL,
    Kbat INT(11) NULL DEFAULT NULL,
    Kgra INT(11) NULL DEFAULT NULL,
    Kbur INT(11) NULL DEFAULT NULL,
    Kres INT(11) NULL DEFAULT NULL,
    Ksec INT(11) NULL DEFAULT NULL,
    Nom VARCHAR(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Prenom VARCHAR(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Matri VARCHAR(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
    DatCre DATETIME NULL DEFAULT NULL,
    DatOuv DATETIME NULL DEFAULT NULL,
    DatMod DATETIME NULL DEFAULT NULL,
    DatClo DATETIME NULL DEFAULT NULL,
    HorSect VARCHAR(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    CodHie SMALLINT(6) NULL DEFAULT NULL,
    CodHor VARCHAR(6) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    LibHor VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Telephone VARCHAR(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Poste VARCHAR(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Fax VARCHAR(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Portable VARCHAR(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Bureau VARCHAR(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    RoleDeta LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    DatMaj DATETIME NULL DEFAULT NULL,
    DatNai DATETIME NULL DEFAULT NULL,
    VilNai VARCHAR(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    DepNai VARCHAR(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    NomPre VARCHAR(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Actif TINYINT(4) NOT NULL,
    IneTP SMALLINT(6) NULL DEFAULT NULL,
    HSLabo SMALLINT(6) NULL DEFAULT NULL,
    MissioLabo TINYINT(4) NOT NULL,
    LogUse VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    NumImmo VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    INSEE VARCHAR(16) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Circe TINYINT(4) NOT NULL,
    PaysNai VARCHAR(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Signat TINYINT(4) NOT NULL,
    Temptation TINYINT(4) NOT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    NumautCond INT(11) NULL DEFAULT NULL,
    Autorise INT(11) NULL DEFAULT NULL,
    INM CHAR(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    AgGesper VARCHAR(12) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    AgRe VARCHAR(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    AgRisques INT(11) NULL DEFAULT NULL,
    Ksec2 INT(11) NULL DEFAULT NULL
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE batiments (
    Kbat INT(11) AUTO_INCREMENT NOT NULL,
    LibBatC VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    LibBat VARCHAR(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    GPS VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
    PRIMARY KEY (Kbat)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE catgrad (
    Kcgr INT(11) AUTO_INCREMENT NOT NULL,
    LibCgr VARCHAR(150) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Kcgr)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE catperm (
    Kcpe INT(11) AUTO_INCREMENT NOT NULL,
    CatPerm CHAR(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    DefPerm LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Kcpe)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE catpiece (
    Kcpi INT(11) AUTO_INCREMENT NOT NULL,
    TypPiece INT(11) NULL DEFAULT NULL,
    CatPiece VARCHAR(150) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Kcpi)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE contacts (
    Kcon INT(11) AUTO_INCREMENT NOT NULL,
    Ksoc INT(11) NOT NULL,
    Nom VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Prenom VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Mel VARCHAR(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Telephone VARCHAR(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Portable VARCHAR(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Fax VARCHAR(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Fonction VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    DatMaj DATETIME NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Kcon)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE db_interim (
    PID INT(11) AUTO_INCREMENT NOT NULL,
    Agent INT(11) NULL DEFAULT NULL,
    Interim INT(11) NULL DEFAULT NULL,
    Final INT(11) NULL DEFAULT NULL,
    D0 DATETIME NULL DEFAULT NULL,
    D1 DATETIME NULL DEFAULT NULL,
    VISA1 INT(11) NULL DEFAULT NULL,
    VISA2 INT(11) NULL DEFAULT NULL,
    VALID INT(11) NULL DEFAULT NULL,
    UID VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    PRIMARY KEY (PID)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE descripchamp (
    Kdes INT(11) AUTO_INCREMENT NOT NULL,
    name VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    haut INT(11) NULL DEFAULT NULL,
    gauche INT(11) NULL DEFAULT NULL,
    largeur INT(11) NULL DEFAULT NULL,
    hauteur INT(11) NULL DEFAULT NULL,
    panel VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    caption VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Descrip LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    indice INT(11) NULL DEFAULT NULL,
    PRIMARY KEY (Kdes)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE domaines (
    ID_DOMAINE DECIMAL(3, 0) NOT NULL,
    NOM_DOMAINE INT(11) NOT NULL,
    PRIMARY KEY (ID_DOMAINE)
) ENGINE=InnoDB COLLATE=utf8_general_ci;
CREATE TABLE droit_consult (
    KConsult INT(11) AUTO_INCREMENT NOT NULL,
    CodeConsult INT(11) NULL DEFAULT NULL,
    LibConsultC CHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    LibConsult CHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    PRIMARY KEY (KConsult)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE etablissements (
    Kets INT(11) AUTO_INCREMENT NOT NULL,
    Kadr INT(11) NULL DEFAULT NULL,
    LibEts TEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    LibEtsC VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Obs LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    etsGESPER VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Archive INT(11) NOT NULL,
    PRIMARY KEY (Kets)
) ENGINE=MyISAM COLLATE=utf8_general_ci;
CREATE TABLE familles (
    Kfam INT(11) AUTO_INCREMENT NOT NULL,
    LibFam VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Kfam)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE feries (
    Kfer INT(11) AUTO_INCREMENT NOT NULL,
    DateFerie DATETIME NULL DEFAULT NULL,
    LibFerie VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    RTT TINYINT(4) NOT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Kfer)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE gestion_droits (
    Kdts INT(11) AUTO_INCREMENT NOT NULL,
    Kage INT(11) NULL DEFAULT NULL,
    DtValid INT(11) NULL DEFAULT NULL,
    DtConsultation INT(11) NULL DEFAULT NULL,
    PRIMARY KEY (Kdts)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE grades (
    Kgra INT(11) AUTO_INCREMENT NOT NULL,
    Kcgr INT(11) NOT NULL,
    LibGrac VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    LibGra VARCHAR(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Gesper VARCHAR(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Statut VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    CatFP VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    TechAdm VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    HSDroit TINYINT(4) NOT NULL,
    Verrou INT(11) NULL DEFAULT NULL,
    PRIMARY KEY (Kgra)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE hierarchie (
    Khie INT(11) AUTO_INCREMENT NOT NULL,
    Kuni INT(11) NULL DEFAULT NULL,
    Ksub INT(11) NULL DEFAULT NULL,
    Kser INT(11) NULL DEFAULT NULL,
    Kage INT(11) NOT NULL,
    Krol INT(11) NOT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Khie)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE historic (
    Khis INT(11) AUTO_INCREMENT NOT NULL,
    LogUse VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    LibHis VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    LibSubc VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    DatExe DATETIME NULL DEFAULT NULL,
    TypExe VARCHAR(3) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Khis)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE interim (
    PID INT(11) AUTO_INCREMENT NOT NULL,
    AGENT INT(11) NULL DEFAULT NULL,
    V1 INT(11) NULL DEFAULT NULL,
    V2 INT(11) NULL DEFAULT NULL,
    PRIMARY KEY (PID)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE medic_cat (
    id INT(11) NOT NULL,
    cat VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE medic_dossiers (
    id INT(11) AUTO_INCREMENT NOT NULL,
    kage INT(11) NOT NULL DEFAULT -1,
    poste_actuel TEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    traitements TEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    tabac VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT '0',
    alcool VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT '0',
    sport VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT '0',
    orientations VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    conclusions VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    date DATE NULL DEFAULT NULL,
    type INT(11) NULL DEFAULT NULL,
    cat INT(11) NULL DEFAULT NULL,
    Taille FLOAT NULL DEFAULT NULL,
    Poids FLOAT NULL DEFAULT NULL,
    Pouls FLOAT NULL DEFAULT NULL,
    TA VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    TA_ORD VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    TA_ORG VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    clinique VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    vaccinations TEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    TA_CORRECTION VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    TA_RQ VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    CVF FLOAT NULL DEFAULT NULL,
    VEMS FLOAT NULL DEFAULT NULL,
    VEMS_CVF FLOAT NULL DEFAULT NULL,
    DEMM FLOAT NULL DEFAULT NULL,
    TU VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    TU_RESULT VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    TV_OD VARCHAR(2) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    TV_OG VARCHAR(2) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    TV_CORRECTION VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    TV_RQ VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    TV_ANOMALIE VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    TV_STIGM VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    commentaires LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    _clinique LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE medic_gen (
    kage INT(11) NOT NULL,
    gen_perso TEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
    gen_family TEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
    PRIMARY KEY (kage)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE medic_type (
    id INT(11) NULL DEFAULT NULL,
    type VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE mela (
    Kmela INT(11) AUTO_INCREMENT NOT NULL,
    Kage INT(11) NOT NULL,
    LibMelA VARCHAR(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Kmela)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE mele (
    Kmele INT(11) AUTO_INCREMENT NOT NULL,
    Kets INT(11) NOT NULL,
    LibMelE VARCHAR(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    PRIMARY KEY (Kmele)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE mels (
    Kmels INT(11) AUTO_INCREMENT NOT NULL,
    Ksub INT(11) NOT NULL,
    LibMelS LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Kmels)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE melu (
    Kmelu INT(11) AUTO_INCREMENT NOT NULL,
    Kuni INT(11) NOT NULL,
    LibMelU LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Kmelu)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE melv (
    Kmelv INT(11) AUTO_INCREMENT NOT NULL,
    Kser INT(11) NOT NULL,
    LibMelV LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Kmelv)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE monblob (
    id_blob INT(11) AUTO_INCREMENT NOT NULL,
    blob BLOB NOT NULL,
    PRIMARY KEY (id_blob)
) ENGINE=InnoDB COLLATE=latin1_swedish_ci;
CREATE TABLE motif (
    kmof INT(11) AUTO_INCREMENT NOT NULL,
    motif VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
    PRIMARY KEY (kmof)
) ENGINE=InnoDB COLLATE=utf8_general_ci;
CREATE TABLE mpaagent (
    id_MPA INT(11) AUTO_INCREMENT NOT NULL,
    Kage INT(11) NOT NULL,
    idMPALOLF INT(11) NULL DEFAULT NULL,
    quotite_MPA INT(11) NULL DEFAULT NULL,
    debut_MPA DATETIME NULL DEFAULT NULL,
    fin_MPA DATETIME NULL DEFAULT NULL,
    delete_MPA TINYINT(4) NOT NULL,
    PRIMARY KEY (id_MPA)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE mpalolf (
    idMPALOLF INT(11) AUTO_INCREMENT NOT NULL,
    codeLOLF VARCHAR(16) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    libMission TEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    libProgramme TEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    libAction TEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    libSousAction TEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    PRIMARY KEY (idMPALOLF)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE old_grades (
    Kgra INT(11) AUTO_INCREMENT NOT NULL,
    Kcgr INT(11) NOT NULL,
    LibGrac VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    LibGra VARCHAR(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Gesper INT(11) NULL DEFAULT NULL,
    Statut VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    CatFP VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    TechAdm VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    HSDroit TINYINT(4) NOT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Kgra)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE param (
    Kpar INT(11) AUTO_INCREMENT NOT NULL,
    SauvSource LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    ImagesCS LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    ImagesWeb LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    PhotosCS LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    PhotoWeb LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    TSource VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    TUser VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    TBDD VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    TPasse VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    TProprio VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    TAcces VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    TServer VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    RSource VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    RUser VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    RBDD VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    RPasse VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    RProprio VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    RAcces VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    RServer VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Kpar)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE param_droits (
    Kparam INT(11) AUTO_INCREMENT NOT NULL,
    Kage INT(11) NULL DEFAULT NULL,
    Param VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Value VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    PRIMARY KEY (Kparam)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE passeport (
    Id INT(11) NOT NULL,
    IdHabilitation INT(11) NULL DEFAULT NULL,
    IdAgent INT(11) NULL DEFAULT NULL,
    IdContact INT(11) NULL DEFAULT NULL,
    Login TINYTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Password TINYTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    UID TINYTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Actif TINYINT(1) NULL DEFAULT NULL,
    DateDerCon DATETIME NULL DEFAULT NULL
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE photo (
    PID INT(11) AUTO_INCREMENT NOT NULL,
    MATRI VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    PHOTO VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    LOCK INT(11) NULL DEFAULT NULL,
    PRIMARY KEY (PID)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE position (
    Kpst INT(11) AUTO_INCREMENT NOT NULL,
    IDPos VARCHAR(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Position VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Description LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Ordre SMALLINT(6) NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Kpst)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE postal (
    Id INT(11) NOT NULL,
    IdDepartement INT(11) NULL DEFAULT NULL,
    IdZone INT(11) NULL DEFAULT NULL,
    Code VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Ville TINYTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE recapitulatif (
    id_recapitulatif INT(11) AUTO_INCREMENT NOT NULL,
    Kage INT(11) NOT NULL,
    Date DATE NOT NULL,
    Session VARCHAR(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
    Nom_organisme VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
    type_formation INT(11) NOT NULL,
    upload LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    PRIMARY KEY (id_recapitulatif)
) ENGINE=InnoDB COLLATE=latin1_swedish_ci;
CREATE TABLE rolconsult (
    kRolConsult INT(11) AUTO_INCREMENT NOT NULL,
    krol INT(11) NULL DEFAULT NULL,
    KConsult INT(11) NULL DEFAULT NULL,
    PRIMARY KEY (kRolConsult)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE roles (
    Krol INT(11) AUTO_INCREMENT NOT NULL,
    CodRol INT(11) NULL DEFAULT NULL,
    LibRolc VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    LibRol VARCHAR(150) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Krol)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE sauvage (
    Ksav INT(11) AUTO_INCREMENT NOT NULL,
    Kuse INT(11) NOT NULL,
    LibSavc VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    LibSav VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    DatSav DATETIME NULL DEFAULT NULL,
    Troncage SMALLINT(6) NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Ksav)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE services (
    Kser INT(11) AUTO_INCREMENT NOT NULL,
    Ksub INT(11) NOT NULL,
    Kadr INT(11) NULL DEFAULT NULL,
    LibSerC VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    LibSer VARCHAR(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Telephone VARCHAR(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Fax VARCHAR(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Obs LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    CodHie INT(11) NULL DEFAULT NULL,
    Chemin LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Archive TINYINT(4) NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    Code VARCHAR(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    PRIMARY KEY (Kser)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE societes (
    Ksoc INT(11) AUTO_INCREMENT NOT NULL,
    Kfam INT(11) NOT NULL,
    Kpos INT(11) NOT NULL,
    LibSocc VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    LibSoc VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Adresse LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Web LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Mel LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Telephone VARCHAR(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Fax VARCHAR(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Ksoc)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE sous_domaines (
    ID_SOUS_DOMAINES DECIMAL(3, 0) NOT NULL,
    ID_DOMAINE DECIMAL(3, 0) NOT NULL,
    NOM_SOUS_DOMAINES INT(11) NOT NULL,
    INDEX FK_APPARTENIR (ID_DOMAINE),
    PRIMARY KEY (ID_SOUS_DOMAINES)
) ENGINE=InnoDB COLLATE=utf8_general_ci;
CREATE TABLE srhmel (
    Ksrh INT(11) AUTO_INCREMENT NOT NULL,
    Kage INT(11) NOT NULL,
    Melanie TINYINT(4) NOT NULL,
    SRHVac TINYINT(4) NOT NULL,
    SRH TINYINT(4) NOT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Ksrh)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE subdis (
    Ksub INT(11) AUTO_INCREMENT NOT NULL,
    Kuni INT(11) NOT NULL,
    Kadr INT(11) NULL DEFAULT NULL,
    LibSubC VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    LibSub VARCHAR(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    HorSect CHAR(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Code CHAR(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Telephone VARCHAR(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Fax VARCHAR(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Obs LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    CodHie INT(11) NULL DEFAULT NULL,
    Chemin LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Archive TINYINT(4) NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    subGESPER VARCHAR(4) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Kets INT(11) NULL DEFAULT NULL,
    PRIMARY KEY (Ksub)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE tempbpc (
    Matri VARCHAR(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    NomPre VARCHAR(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    DatCre DATETIME NULL DEFAULT NULL,
    DatOuv DATETIME NULL DEFAULT NULL,
    DatMod DATETIME NULL DEFAULT NULL,
    DatClo DATETIME NULL DEFAULT NULL,
    Horcode VARCHAR(6) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    LibCourt VARCHAR(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    IneTP SMALLINT(6) NULL DEFAULT NULL,
    InHS SMALLINT(6) NULL DEFAULT NULL,
    DatHophJou DATETIME NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE travaille (
    ID_SOUS_DOMAINES DECIMAL(3, 0) NOT NULL,
    ID_MATRICULE INT(11) NOT NULL,
    INDEX FK_TRAVAILLE2 (ID_MATRICULE),
    PRIMARY KEY (ID_SOUS_DOMAINES, ID_MATRICULE)
) ENGINE=InnoDB COLLATE=utf8_general_ci;
CREATE TABLE trombi (
    kage INT(11) NOT NULL,
    trombi LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    PRIMARY KEY (kage)
) ENGINE=InnoDB COLLATE=latin1_swedish_ci;
CREATE TABLE type_formation (
    id_formation INT(11) AUTO_INCREMENT NOT NULL,
    Libelle VARCHAR(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
    frequence INT(11) NOT NULL,
    PRIMARY KEY (id_formation)
) ENGINE=InnoDB COLLATE=latin1_swedish_ci;
CREATE TABLE unites (
    Kuni INT(11) AUTO_INCREMENT NOT NULL,
    Kadr INT(11) NULL DEFAULT NULL,
    LibUnic VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    LibUni VARCHAR(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Telephone VARCHAR(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Fax VARCHAR(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Obs LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    CodHie INT(11) NULL DEFAULT NULL,
    Chemin LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Archive TINYINT(4) NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    uniGESPER VARCHAR(8) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Code VARCHAR(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Kets INT(11) NULL DEFAULT NULL,
    PRIMARY KEY (Kuni)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE useannex (
    Kuseann INT(11) AUTO_INCREMENT NOT NULL,
    Kuse INT(11) NOT NULL,
    Kann INT(11) NOT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Kuseann)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE users (
    Kuse INT(11) AUTO_INCREMENT NOT NULL,
    Kage INT(11) NOT NULL,
    IdPasseport INT(11) NOT NULL,
    DatDerCon DATETIME NULL DEFAULT NULL,
    Activite TINYINT(4) NOT NULL,
    Admin TINYINT(4) NOT NULL,
    Srh TINYINT(4) NOT NULL,
    Unite TINYINT(4) NOT NULL,
    SPMG TINYINT(4) NOT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    Consult TINYINT(4) NULL DEFAULT NULL,
    CFA TINYINT(4) NOT NULL,
    PRIMARY KEY (Kuse)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE vehassu (
    Kvas INT(11) AUTO_INCREMENT NOT NULL,
    NomAss VARCHAR(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Kvas)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE vehmark (
    Kvmk INT(11) AUTO_INCREMENT NOT NULL,
    Marque VARCHAR(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Kvmk)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE vehmod (
    Kvmd INT(11) AUTO_INCREMENT NOT NULL,
    Kvmk INT(11) NOT NULL,
    Modele VARCHAR(250) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    CV INT(11) NULL DEFAULT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Kvmd)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE versions (
    Kver INT(11) AUTO_INCREMENT NOT NULL,
    LibVer VARCHAR(200) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    DatVer DATETIME NULL DEFAULT NULL,
    Numero VARCHAR(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Obs LONGTEXT CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
    Activite TINYINT(4) NOT NULL,
    Verrou TINYBLOB NULL DEFAULT NULL,
    PRIMARY KEY (Kver)
) ENGINE=MyISAM COLLATE=latin1_swedish_ci;
CREATE TABLE visiom (
    kage INT(11) NOT NULL,
    LIBELLE_POSTE VARCHAR(73) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
    FAMILLE_PROF VARCHAR(46) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
    EMPLOI_TYPE VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
    REHUCIT VARCHAR(23) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
    NOM VARCHAR(16) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
    PRENOM VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
    DATE_NAISSANCE VARCHAR(23) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL
) ENGINE=MyISAM COLLATE=utf8_general_ci;
CREATE TABLE vm (
    kvm INT(11) AUTO_INCREMENT NOT NULL,
    kage INT(11) NOT NULL,
    nature_visite INT(11) NOT NULL,
    date_visite DATE NULL DEFAULT NULL,
    heure_visite TIME NULL DEFAULT NULL,
    resultats INT(11) NULL DEFAULT NULL,
    commentaires VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
    PRIMARY KEY (kvm)
) ENGINE=MyISAM COLLATE=utf8_general_ci;
CREATE TABLE vm_natures (
    kvm_natures INT(11) AUTO_INCREMENT NOT NULL,
    nature VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
    PRIMARY KEY (kvm_natures)
) ENGINE=MyISAM COLLATE=utf8_general_ci;
CREATE TABLE vm_resultats (
    kvm_resultats INT(11) AUTO_INCREMENT NOT NULL,
    resultat VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
    PRIMARY KEY (kvm_resultats)
) ENGINE=MyISAM COLLATE=utf8_general_ci;
ALTER TABLE sous_domaines ADD CONSTRAINT FK_APPARTENIR FOREIGN KEY (ID_DOMAINE) REFERENCES domaines (ID_DOMAINE) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE travaille ADD CONSTRAINT FK_TRAVAILLE FOREIGN KEY (ID_SOUS_DOMAINES) REFERENCES sous_domaines (ID_SOUS_DOMAINES) ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT FK_TRAVAILLE2 FOREIGN KEY (ID_MATRICULE) REFERENCES agents (ID_MATRICULE) ON UPDATE NO ACTION ON DELETE NO ACTION;
